[package]
name = "path-trie-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "path_trie"

[dev-dependencies]
itertools = "0.12.0"
